version: '3'
services:
  web:
    image: chimerast/niconico-speenya
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      SERVER_URL: http://localhost:8080
    ports:
      - 8080:8080
    volumes:
      - ./data/:/app/data/
